- contributorlist
Hi, I'd love for you to accept my pull request. Thanks!
> Add Manish Pokhrel to the contributor list

- Java/SelectionSort.java
> new java file added

- Java/Armstrong.java
- Java/LowerTriangularMatrix.java
- contributorlist
I added a program to display lower triangular matrix Java/LowerTriangularMatrix.java
fixed a bug in Java/Armstrong.java
added my name in contributor list
> LowerTriangularMatrix problem

- Java/insertionsort.java
> Added new file

- Java/Binary_Search.java
Binary Search is an Optimised searching algorithm, so it should be there in your repo
> Request to add Binary Search Algo

- Java/LinearSearch.java
Linear search is a searching algorithm with Linear time complexity & come's in mind as a brute force for everyone.
> Request to add Linear Search

- Paper_Scissor_Rock_game.java
Using java I have made a paper_scissor_rock game
> added paper_scissor_rock game.java

- AVL Tree/AVL_Tree.cpp
insertion and deletion of AVL tree is added
> AVL tree cpp

- PrintSubsequenceOfSumK.java
Please accept my code for #Hacktoberfest2022 #Hacktoberfest2022-accept
> This program prints the subsequence of a given array with sum k(target)

- Cpp/Magic_square_generator.cpp
- Cpp/Next_permutation.cpp
- contributorlist
I have added the solution to the Leetcode problem **Next permutation**.
> Added Next permutation problem

- Java/tictactoe.java
I hope I didn't violate any rules and I hope my PR get merged so it can be counted towards hacktoberfest2022.
> added tictactoe game

- Cpp/Greedy Algorithms/Dijkstra_algorithm.cpp
Thank you for reading my pull request.
Added Dijkstra Algorithm in C++.
> added Dijkstra Algorithm in C++

- Java/JumpSearch.java
Jump search.
Happy Hacktoberfest!
> Jump Search in java

- Cpp/Programs/two sum.cpp
- contributorlist
> added name

- Cpp/preorderTraversal.cpp
Please accept my PR and provide Hacktoberfest label. Thanks
> Added program for preorder tree traversal

- Cpp/Sliding Window/Longest_Repeating_Character_Replacement.cpp
Hii @Tanay-Gupta. Please merge my PR.
I want to contribute in the problem Longest Repeating Character Replacement in Cpp.
Thank you!!
> Longest Repeating Character Replacement

- hello world.cpp
- resize array.cpp
- string characters.cpp
- volume of boxes.cpp
This code will resize the array and populate half of array by user given values and next half by twice of given values .
> Resizing array

- hello world.cpp
- string characters.cpp
This program will take string of characters as input from user, and a key to display characters till key(substring) .
> String characters

- hello world.cpp
- string characters.cpp
- volume of boxes.cpp
This code illustrates a class BOX , with all setters and getters , creates an object of dynamic array of boxes , stores all values and then sorting volume of all boxes in an ascending order .
> Volume of boxes

- Cpp/Function_binary_&_selection.c
> Function_binary_&_selection

- Cpp/Scramble_String.cpp
- Cpp/wildcard_matching.cpp
I want to add Dynamic Programming questions
> Dynamic Programming

- Cpp/Programs/IdentityMatrix.cpp
This program dynamically allocates a 2D array & determines whether it is identity matrix or not.
> Identity Matrix or Not

- Cpp/Programs/pascalTriangle.cpp
This c++ program prints the Pascal's triangle with 'n' rows.
> pascalTriangle.cpp

- Cpp/Dynamic Programming/closestPairProblem.cpp
Added DP Solution i.e, Closest Pair Problem
> Added Closest Pair Problem

- selection_sort.cpp
>  selection_sort.cpp

- Python/sleep and emotion detector/face_emotion_recognition.py
In this file, I have uploaded two OpenCV projects in which one program is used to detect weather a person is sleeping or not, and another program is used to detect the emotion of the person
> OpenCV projects added

- Contests/codechef solutions/codechef_fireesc.cpp
Thank you for reading my pull request, please merge my request. codechef question link is attached.
https://www.codechef.com/problems/FIRESC
> A new file added in codechef contest solutions

- Contests/codechef solutions/Paper_cutting.cpp
Thank you for reading my pull request.
please merge my pull request.
> Added a new file in codechef solution

- Java/PermutationOfArray.java
- Java/PhoneKeyPadProblem.java
- Java/RatMazeProblem.java
- Java/SubsequenceThroughRecursion.java
- Phone Keypad Problem
- Subsequence Problem
- Rat Maze Problem
- Permutation of a Array
> some recursion problem solution added
